### ISSUE TITLE
invaild login..

### ISSUE THREAD

**Issue by anthonymoon** [syepes/VSphere2Metrics#10]
Seems like no matter what I try, I keep getting the invalid login error:

vcs.urls                   = ['https://zeppo.vanh.mpc.local/sdk']
vcs.user                   = 'api'
vcs.pwd                    = '!Password1'                // Generated password
vcs.timezone               = 'GMT-7'
vcs.perfquery_timeout      = 60                // Metrics retrieval timeout in Seconds
vcs.perf_max_samples       = 1                // Last 1 Minute (3x20s = 60s)
                                               // Last 2 Minute (6x20s = 120s)
                                               // Last 5 Minute (15x20s = 300s)
                                               // Last 10 Minute (30x20s = 600s)

10:47:28 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
10:47:28 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://zeppo.vanh.mpc.local/sdk
10:47:55 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
10:47:55 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://zeppo.vanh.mpc.local/sdk
10:48:21 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
10:48:21 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://zeppo.vanh.mpc.local/sdk
10:48:48 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
10:48:48 [zeppo]                    ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://zeppo.vanh.mpc.local/sdk

Is this software able to connect directly to ESXi hosts, or does it need to connect back to vcenter?

Thanks

**Comment by syepes** [comment]
Have you encrypted the password?  https://github.com/syepes/VSphere2Metrics/issues/3
