### ISSUE TITLE
VSphere2Metrics values don't match Resource manager

### ISSUE THREAD

**Issue by timdicon** [syepes/VSphere2Metrics#11]
I'm using VSphere2Metrics dumping to an InfluxDB.  using various tools listed in https://blogs.msdn.microsoft.com/vijaysk/2012/10/26/tools-to-simulate-cpu-memory-disk-load/ . With them I'm generating specific load on a VM, measuring using resource manager, then comparing those figures with influxDB.

For % VM memory used, on the VM I'm generating a constant 45%, yet in grafana using the query below I see values > 100%!

SELECT mean("value") AS "value" FROM "mem_usage_average-percent" WHERE "server" =~ /$server$/ AND $timeFilter GROUP BY time($interval), "server"

Also, Using SQLIO to generate IO/throughput and the following grafana queries

SELECT mean("value") AS "value" FROM "virtualDisk_write_average-kiloBytesPerSecond" WHERE "server" =~ /$server$/ AND $timeFilter GROUP BY time($interval), "server"
SELECT mean("value") AS "value" FROM "virtualDisk_read_average-kiloBytesPerSecond" WHERE "server" =~ /$server$/ AND $timeFilter GROUP BY time($interval), "server"
SELECT mean("value") AS "value" FROM "virtualDisk_numberWriteAveraged_average-number" WHERE "server" =~ /$server$/ AND $timeFilter GROUP BY time($interval), "server"
etc..

again I see very different values comparing against resource manager/the output of SQLIO.

Any ideas on why I'm seeing the mis-match?

Thanks Tim

**Comment by timdicon** [comment]
by changing the destination type to Graphite instead of InfluxDB, and having a quick look at the following grafana queries

 "target": "ESXi.lab-02.Guest.labmssql-01.cpu.avg.usage_average-percent"
 "target": "ESXi.lab-01.Guest.labmssql-01.mem.avg.usage_average-percent"
 "target": "ESXi.lab-02.Guest.labmssql-01.virtualDisk.avg.write_average-kiloBytesPerSecond"
 "target": "ESXi.lab-02.Guest.labmssql-01.virtualDisk.scsi0-0.write_average-kiloBytesPerSecond"
 "target": "ESXi.lab-01.Host.cpu.avg.usage_average-percent"

Only the guest mem.avg.usage_average-percent and host cpu.avg.usage_average-percent are displaying any stats (values for both are way > 100% too)

looking in the log file, there are only entries related to NFS datastores referenced in https://github.com/syepes/VSphere2Metrics/issues/7 

hope this helps!

Thanks, Tim

**Comment by syepes** [comment]
@timdicon What version of VC are you usings?
The only issue would be if you were using v4.x as after this version some metrics changed scale. 

This app just collects the raw 20sec "RealTime" values not the aggregates from the VC and sends them to the destination, you have to compare the values with the once on the VC Console "RealTime".

The #7 can be ignored and will have no affect on the values.

<s>I will try an upload some example Grafana dashboards when I get tome free time.</s>
I have just added some templates: https://github.com/syepes/VSphere2Metrics/tree/master/grafana

**Comment by timdicon** [comment]
Hi,

the LAB env I'm testing on is ver 5.5.

Thanks for the dashboards, I'm going through those, and I notice a few issues for my setup, a large amount of the graphs aren't producing any stats / are missing stats.  

E.g.  
for graph Disk IOPS in the ESXi.GuestPerf dashboard the query is 
"target": "alias(sumSeries(ESXi.[[ESXi]].Guest.[[VM]].disk.disk.*.{numberReadAveraged_average-number,numberWriteAveraged_average-number}),'Sum')"

However in my graphite DB within ESXi.[[ESXi]].Guest.[[VM]].disk for every VM there is only a folder for avg, no disk, and within avg a single wsp file maxTotalLatency_latest-millisecond.wsp. nothing else..

Any ideas on why I'm missing some of the stats you are seeing?

Thanks Tim

**Comment by syepes** [comment]
@timdicon Thats very strange, there must be some kind of issue with you VC or account, VSphere2Metrics has been battle tested and there should be no know issues.
- The only thing I would suggest is to verify the account you are using, it should have read access to all..
- Run `./VSphere2Metrics -dc >counters.txt` and `./VSphere2Metrics -dm >metrics.txt` and if you see the counters/metrics then your issue is with the Graphite/InfluxDB..

**Comment by timdicon** [comment]
The user is in the administrator role..  and the info within metrics.txt for a string with disk. is only this 

		disk.avg.maxTotalLatency_latest-millisecond:

We have multiple VCs, I will test with another one tomorrow and see what metrics/counters I get from that instance.

Thanks so far :) Tim

**Comment by timdicon** [comment]
The account is in the administrator role... If I search the metrics outputs for string disk. I only see the below multiple times.

```
    disk.avg.maxTotalLatency_latest-millisecond:
```

I have multiple VCs, I will test with another one tomorrow. 

Thanks for the help so far.

**Comment by timdicon** [comment]
however, looking in counters, I see counters like below.. I guess I should be seeing more in the metrics?

_Counter ID: 136
    MetricId=136
    Metric=disk.numberReadAveraged_average-number
    RollupType=average
    Level=1
    PerDeviceLevel=3
    StatsType=rate
    UnitInfo=number
    NameInfo=numberReadAveraged
    GroupInfo=disk
Counter ID: 137
    MetricId=137
    Metric=disk.numberWriteAveraged_average-number
    RollupType=average
    Level=1
    PerDeviceLevel=3
    StatsType=rate
    UnitInfo=number
    NameInfo=numberWriteAveraged
    GroupInfo=disk_

**Comment by syepes** [comment]
@timdicon If you can send me the output of both -dc & -dm by email so I can have a look if a see anything strange.

**Comment by syepes** [comment]
I will be releasing the version 1.6.0 in the next weeks, please test it again it has fixed several issues.
