### ISSUE TITLE
java 1.8 report SLF4J error - stuck at encyrpting password :(

### ISSUE THREAD

**Issue by MrDibbley** [syepes/VSphere2Metrics#12]
java -jar vsphere2metrics.jar -pwd bob
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/tmp/vsphere2metrics-1.6.0/vsphere2metrics.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.

**Comment by syepes** [comment]
Use the [built jar](https://github.com/syepes/VSphere2Metrics/releases/download/1.6.0/vsphere2metrics-1.6.0.zip) it sould work.
There is an issue with the last version of slf4j I have to fix this in the next release.

**Comment by MrDibbley** [comment]
thats the one im using :(, im running on redhat 7.3 with java-1.8.0-ibm-1.8.0.4.5-1jpp.1.el7_3.x86_64 ?

tried on a winblows 7 box with java 1.8.0.131 and works fine?

C:\\vsphere2metrics-1.6.0\vsphere2metrics-1.6.0>java -jar vsphere2metrics.jar -pwd bob
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to1.8.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/cs123nh/Downloads/vsphere2metrics-1.6.0/vsphere2metrics-1.6.0/vsphere2metrics.jar!/org/slf4j/impl/StaticLog
gerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
mNAOHF5bARhMHOut6em/PA==

**Comment by syepes** [comment]
@MrDibbley Just pushed a new release that should fix this issue:
https://github.com/syepes/VSphere2Metrics/releases/tag/1.6.1
