### ISSUE TITLE
host names truncated

### ISSUE THREAD

**Issue by infernix** [syepes/VSphere2Metrics#14]
Hi,

It seems that if an ESXi host is called '10.20.30.40', the metric name gets truncated to '10'; this causes metrics for multiple hosts to be aggregated under the same metric name.

E.g. graphite:

`ESXi.clustered.test01.Host.10.power.avg.power_average-watt`

There are 4 esxi hosts in `test01` and they are named 10.20.30.41/42/43/44 but only `Host.10.` shows up.

**Comment by infernix** [comment]
Also, further investigation seems to show the exact same problem for guests:

`ESXi.clustered.test01.Guest.testvm-10.cpu.avg.usage_average-percent`

We have 4 vms called `testvm-10.20.30.x` where x = 51/52/53/54. Same thing seems to happen.

**Comment by infernix** [comment]
FWIW I would suggest that for graphite, `.` could be replaced with `_` so as to not create new nodes; for influxdb, tags should support dots just fine but it may need proper quoting or something.

**Comment by syepes** [comment]
@infernix VSphere2Metrics was not designed to work with host/guest named with IP's what's why it messing up your metrics. if I have some free time I'll try to fix this to replace the '.' with '_'

**Comment by infernix** [comment]
The issue is here:

`Closure cleanName = { String str -> str?.split('\\.')?.getAt(0)?.trim().replaceAll(~/[\s-\.]/, "-")?.toLowerCase() }`

Not very familiar with java syntax but it appears that you're splitting at the first dot, e.g. trying to keep only the hostname of a FQDN?

So here's a trivial fix:

```diff
diff --git a/src/main/groovy/VSphere2Metrics.groovy b/src/main/groovy/VSphere2Metrics.groovy
index a9673fb..8be2f3f 100644
--- a/src/main/groovy/VSphere2Metrics.groovy
+++ b/src/main/groovy/VSphere2Metrics.groovy
@@ -53,7 +53,7 @@ class VSphere2Metrics {
   MetricClient mc,mcG,mcI
   LinkedHashMap selfMon = [:]
 
-  Closure cleanName = { String str -> str?.split('\\.')?.getAt(0)?.trim().replaceAll(~/[\s-\.]/, "-")?.toLowerCase() }
+  Closure cleanName = { String str -> str?.trim().replaceAll(~/[\s-\.]/, "-")?.toLowerCase() }
 
 
   /**
```

Whether if you want to make that into an option I'll leave to you; personally I don't see any reason to split up the hostname ever :)

**Comment by syepes** [comment]
Right on the spot, I decided to use only the HOST and not the FQDN as in many cases the it gets more complicated when querying the data.

I'll have to figure out a way to make it work with either IP's or HOSTS
