### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by eschek87** [syepes/VSphere2Metrics#15]
Hi,

got the following error if I use graphite as datasource:

ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Building metrics: No signature of method: groovy.json.internal.LazyMap.toBigDecimal() is applicable for argument types: () values: []

**Comment by syepes** [comment]
I have rebuild the binary to include this fix : https://github.com/syepes/VSphere2Metrics/releases/download/1.6.1/vsphere2metrics-1.6.1.zip
