### ISSUE TITLE
Connection Issue , connecting Virtual Center 6

### ISSUE THREAD

**Issue by skares** [syepes/VSphere2Metrics#3]
Hi,
would you please help me, i cannot get the Data Collection from a Virtual Center 6.0 Update 1 working.
Is there a way to debug this ? The User and Password i use are correct.

ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
15:07:14 [VC Hostname]               ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://vc.domain.com/sdk

In the log file the following output comes.
01-04-2016 - 15:12:14.165 6365:[main] INFO  com.allthingsmonitoring.vmware.VSphere2Metrics - Start Collecting vSphere Metrics in parallel using PoolSize: 1/5 (Current/Max) / Last execution time: 25.126 seconds
01-04-2016 - 15:12:38.301 6365:[wi12itis04] ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
01-04-2016 - 15:12:38.302 6365:[wi12itis04] ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://vc.domain.com/sdk
01-04-2016 - 15:12:38.3036365:[main] INFO  com.allthingsmonitoring.vmware.VSphere2Metrics - Finished Collecting and Sending vSphere Metrics in 24.139 seconds

thanks a lot Sven

**Comment by syepes** [comment]
@skares Have you encrypted the password used in the config file?

```
java -jar VSphere2Metrics-1.5.3.jar -pwd PasswordToEncrypt
QxWOrUvrKawZ/vPZaaPDKje9n3t5PD4yqlPMIYqxtJQ=
```

```
config.groovy:
vcs.urls              = ['https://vc.domain.com/sdk']
vcs.user              = 'DOMAIN\\user'
vcs.pwd               = 'QxWOrUvrKawZ/vPZaaPDKje9n3t5PD4yqlPMIYqxtJQ='
```

**Comment by skares** [comment]
No i haven't ! I will try this! Thanks for you help !
best Sven

**Comment by syepes** [comment]
@skares No problem, tell me if it works.

**Comment by skares** [comment]
Now it works, perfect thanks a lot!
