### ISSUE TITLE
grafana dashboard example

### ISSUE THREAD

**Issue by ragesaq** [syepes/VSphere2Metrics#4]
Is there an exported grafana dashboard that I can use to get started with the different metric visualization?
Thanks

**Comment by syepes** [comment]
@ragesaq I will upload this week some example Grafana dashboards I personally use.

**Comment by skares** [comment]
That would be a good Idea! +1

**Comment by timdicon** [comment]
Hi, are there any dashboards that we can import?

**Comment by syepes** [comment]
https://github.com/syepes/VSphere2Metrics/tree/master/grafana
