### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by finish06** [syepes/VSphere2Metrics#5]
I have set all the parameters in config.groovy, i.e.
`
vcs.urls                   = ['https://vcenter.****.******:443/sdk']
vcs.user                   = 'trek@vsphere.local'
vcs.pwd                    = '**********'                // Generated password
vcs.timezone               = 'GMT-6'
vcs.perfquery_timeout      = 60                // Metrics retrieval timeout in Seconds
vcs.perf_max_samples       = 15                // Last 1 Minute (3x20s = 60s)
`

I am still unable to login though ... I keep getting the following error:
ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin

**Comment by syepes** [comment]
@finish06 Have you encrypted the password?  https://github.com/syepes/VSphere2Metrics/issues/3
