### ISSUE TITLE
HowTo?

### ISSUE THREAD

**Issue by exbane** [syepes/VSphere2Metrics#6]
Good afternoon,

I'm attempting to do exactly what your project is describing. Pull all metrics from my vSphere Infrastructure and push them to InfluxDB. I don't see any documentation though on how to get this setup.. Can you provide some steps as to how I would go about this?

Thank you!

exbane

**Comment by syepes** [comment]
@exbane With VSphere2Metrics its very simple:
- Modify the example configuration file "config.groovy" that comes in the zip and don't forget to encrypt your password (https://github.com/syepes/VSphere2Metrics/issues/3)
- Configure the Metric destination type, host...
- Create the InfluxDB and CQ's (https://github.com/syepes/VSphere2Metrics/wiki/InfluxDB)
- Start the VSphere2Metrics daemon process (./VSphere2Metrics) without any parameters
- Now start enjoying your stats ;-)

**Comment by exbane** [comment]
Great thank you very much! i do get an error when i attempt to run ./VSphere2Metrics script.. 

[root@graf-vm201 dist]# ./VSphere2Metrics
tee: logs/VSphere2Metrics_console.log: No such file or directory
Error: Unable to access jarfile /opt/VSphere2Metrics/VSphere2Metrics-1.5.2.jar

I'm sure im doing something wrong :) 

Thank you!

**Comment by syepes** [comment]
@exbane  do a "mkdir logs" where ever you installed VSphere2Metrics

**Comment by exbane** [comment]
That got rid of the first error :) now i still get the jarfile error.

Error: Unable to access jarfile /opt/VSphere2Metrics/VSphere2Metrics-1.5.2.jar.. It doesnt appear to exist in that directory.. Do i need to generate the jar or should it be included in the download?

**Comment by syepes** [comment]
@exbane Ahh small Bug, edit the VSphere2Metrics file and change the last line: VSphere2Metrics-1.5.2.jar -> VSphere2Metrics-1.5.3.jar

**Comment by exbane** [comment]
Will do :) let you know if everything works!

**Comment by exbane** [comment]
Same error :( 

[root@graf-vm201 dist]# ./VSphere2Metrics
Error: Unable to access jarfile /opt/VSphere2Metrics/VSphere2Metrics-1.5.3.jar

Here is what the root directory looks like.
[root@graf-vm201 VSphere2Metrics]# ls
build.gradle  CHANGELOG.md  libs  LICENSE.md  logs  README.md  src

**Comment by syepes** [comment]
@exbane You have downloaded the Source not the Binary release:
- Download this: https://github.com/syepes/VSphere2Metrics/releases/download/v1.5.3/VSphere2Metrics-1.5.3.zip
- In the folder /opt/VSphere2Metrics/ you should only see:

```
VSphere2Metrics-1.5.3.jar
config.groovy
VSphere2Metrics
README.md
CHANGELOG.md
LICENSE.md
```

**Comment by exbane** [comment]
doh.. well that's probably why?! :) thank you.

**Comment by exbane** [comment]
Okay i have the proper zip downloaded now - i changed the VSphere2Metrics file to 1.5.3 instead of 1.5.2 and now i get the following..

[root@graf-vm201 VSphere2Metrics]# ./VSphere2Metrics
: No such file or directorycd: /opt/VSphere2Metrics/
./VSphere2Metrics: line 4: $'\r': command not found
./VSphere2Metrics: line 6: $'\r': command not found
./VSphere2Metrics: line 9: $'\r': command not found
./VSphere2Metrics: line 12: $'\r': command not found
./VSphere2Metrics: line 15: $'\r': command not found
./VSphere2Metrics: line 16: $'\r': command not found
'mproperly specified VM option 'MaxGCPauseMillis=200
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[root@graf-vm201 VSphere2Metrics]#

**Comment by syepes** [comment]
Ahh the file VSphere2Metrics is in DOS format, just create a new one: 

rm -f /opt/VSphere2Metrics/VSphere2Metrics
vi /opt/VSphere2Metrics/VSphere2Metrics

VSphere2Metrics - content

```
cd /opt/VSphere2Metrics
export JAVA_HOME=/usr/java/latest
export PATH=$JAVA_HOME/bin:$PATH

export JAVA_OPTS="-d64 -server -Xms2g -Xmx6g -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+UseStringDeduplication -XX:+ExplicitGCInvokesConcurrent -XX:+ScavengeBeforeFullGC"

java $JAVA_OPTS -Dpid=$$ -Dapp.env=PROD -jar $PWD/VSphere2Metrics-1.5.3.jar $* 2>&1 |tee -a logs/VSphere2Metrics_console.log
```

---

**Comment by exbane** [comment]
Awesome i got further! i think my next problem could be an authentication problem.. 

14-04-2016 - 16:47:43.054 [graf-vm201] 19083:[main] INFO  com.allthingsmonitoring.vmware.VSphere2Metrics - Start Collecting vSphere Metrics in parallel using PoolSize: 1/5 (Current/Max) / Last execution time: 0
14-04-2016 - 16:47:48.607 [graf-vm201] 19083:[vcpoc201] ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
14-04-2016 - 16:47:48.615 [graf-vm201] 19083:[vcpoc201] ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://vcpoc201.ops.global.ad/sdk
14-04-2016 - 16:47:48.633 [graf-vm201] 19083:[main] INFO  com.allthingsmonitoring.vmware.VSphere2Metrics - Finished Collecting and Sending vSphere Metrics in 5.621 seconds
14-04-2016 - 16:47:51.626 [graf-vm201] 19083:[Thread-1] INFO  com.allthingsmonitoring.vmware.VSphere2Metrics - Shuting down app...

I made the timezone the same as vCenter which is UTC - didnt know if SSO had to match the time with the client - that didnt work though.. I know the user account im using works to login to vSphere.. ill keep muckin around with it
thank you for your help.

**Comment by syepes** [comment]
By the way I have just update the binary release to include minor fixes:
https://github.com/syepes/VSphere2Metrics/releases/download/v1.5.3/VSphere2Metrics-1.5.3.zip

**Comment by exbane** [comment]
excellent - thank you!

**Comment by exbane** [comment]
@syepes For some reason i'm still running into this error..

09:54:07 [vcpoc201]                 ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Remote exception: VI SDK invoke exception:com.vmware.vim25.InvalidLogin
09:54:07 [vcpoc201]                 ERROR com.allthingsmonitoring.vmware.VSphere2Metrics - Error establishing connection to the vSphere server: https://vcpoc201.ops.global.ad/sdk

Thoughts? i've double checked the user account im using and it works for connecting into vCenter just fine.. I am running vSphere 6

**Comment by exbane** [comment]
Could it have something to do with the fact that i'm using the default vCenter certificate and it can't authenticate against it? is there a way in the script to ignore the certificate?

**Comment by syepes** [comment]
@exbane Did you encrypt your password in config file? Is you user in a domain or just local?

**Comment by exbane** [comment]
@syepes 
i was just using a test user for the connection so i didnt encrypt the password - how would i go about doing that? i've tried both domain and vsphere.local accounts for connecting.

**Comment by syepes** [comment]
You have to encrypt the user password that goes in the config file, have a look at: https://github.com/syepes/VSphere2Metrics/issues/3#issuecomment-204402567

This should resolve your issue

**Comment by exbane** [comment]
That worked! Thank you :) 

i can see the information in grafana - just not seeing any stats yet.. checked the log files for vsphere2metrics and it appears to be sending all the metrics to influxdb successfully.. trying to figure out the influxdb query to properly view the value data to see if its getting in there correctly.. Also i'm using influxdb 0.12 - is that supported? if not i can deploy a 0.8 or 0.9 server for it.

**Comment by exbane** [comment]
actually i found the data.. it was just set to GMT time still i think.. I set vCenter to use US/Eastern and i set the config.groovy file to use US/Eastern but thats not working.. thoughts?

**Comment by syepes** [comment]
@exbane VSphere2Metrics only support the Line Protocol (0.9+ --> 0.1x+)
The setting "vcs.timezone" is used to convert your desired TZ, you can use the parameter "--dumpmetrics" to debug the time conversion by verifying the timestamp (epoch) do that it corresponds to you time...

```
./VSphere2Metrics -h
usage: [-dc] [-dm] [-sf <(1..60) Minutes>] [No paramaters Run as Daemon]
 -dc,--dumpcounters       Dump available counters, OPTIONAL
 -dm,--dumpmetrics        Dump Metrics, OPTIONAL
 -h,--help                Usage information
 -pwd <Password>          Encrypt config password
 -sf,--startfrom <Mins>   Start from last samples (Real-Time (1..60)min),
```
