### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by anthonymoon** [syepes/VSphere2Metrics#9]
Hey all,

the documentation isn't too clear.. but what is required to successfully build this?

**Comment by syepes** [comment]
@anthonymoon You don't have to actually build it, you can download the built ones: https://github.com/syepes/VSphere2Metrics/releases

If you actually want ot build it from source you will need to install (Gradle)[http://bryanlor.com/blog/gradle-tutorial-how-install-gradle-windows] and then just run `gradle build`
